// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.Models;

namespace Project1.Migrations
{
    [DbContext(typeof(TourDbContext))]
    [Migration("20210314230343_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("Project1.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TourTime")
                        .HasColumnType("TEXT");

                    b.HasKey("TourId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Project1.Models.TourGroup", b =>
                {
                    b.Property<int>("TourGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TourSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourGroupId");

                    b.HasIndex("TourId");

                    b.ToTable("TourGroups");
                });

            modelBuilder.Entity("Project1.Models.TourGroup", b =>
                {
                    b.HasOne("Project1.Models.Tour", null)
                        .WithMany("Groups")
                        .HasForeignKey("TourId");
                });
#pragma warning restore 612, 618
        }
    }
}
